export const environment = {
  production: true,
  name: 'queriescare',
  domain: 'queriescare.com',
  appBaseUrl: '/',
  // apiBaseLink: 'http://localhost:4401',
  // ftpBaseLink: 'http://localhost:4401',
  apiBaseLink: 'https://api.alaribah.com',
  ftpBaseLink: 'https://api.alaribah.com',
  userBaseUrl: '/',
  userProfileUrl: '/my-profile',
  userLoginUrl: '/login',
  adminLoginUrl: 'login',
  adminBaseUrl: '/',
  storageSecret: 'SOFT_2021_IT_1998',
  adminTokenSecret: 'SOFT_ADMIN_1995_&&_SOJOL_dEv',
  userTokenSecret: 'SOFT_ADMIN_1996_&&_SOBUR_dEv',
  apiTokenSecret: 'SOFT_API_1998_&&_SAZIB_dEv',
  VERSION: 1
};
